apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-app-deployment
  labels:
    app: node-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: node-app
  template:
    metadata:
      labels:
        app: node-app
    spec:
      containers:
      - name: node-app
        image: <AWS_ACCOUNT_ID>.dkr.ecr.us-west-2.amazonaws.com/my-node-app:latest
        ports:
        - containerPort: 3000